### ISSUE TITLE
bug: `list-devices` command exits with panic

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/ikaros#34]
Log:

```bash
kbdharun@vanillaos:~$ ikaros list-devices
 ▀ Listing devices and drivers... (0s)panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/vanilla-os/ikaros/core.DriversManager.GetLshw({}, {0x77ae50, 0x7})
	/__w/Ikaros/Ikaros/core/manager.go:42 +0x6b4
github.com/vanilla-os/ikaros/core.DriversManager.GetDisplayDevices(...)
	/__w/Ikaros/Ikaros/core/manager.go:69
github.com/vanilla-os/ikaros/core.DriversManager.GetDevices({})
	/__w/Ikaros/Ikaros/core/manager.go:74 +0x2e
github.com/vanilla-os/ikaros/cmd.listDevices(0xc000140000?, {0x779af0?, 0x4?, 0x779af4?})
	/__w/Ikaros/Ikaros/cmd/list-devices.go:39 +0xd5
github.com/spf13/cobra.(*Command).execute(0xc000004c00, {0xa95640, 0x0, 0x0})
	/__w/Ikaros/Ikaros/vendor/github.com/spf13/cobra/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
	/__w/Ikaros/Ikaros/vendor/github.com/spf13/cobra/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/__w/Ikaros/Ikaros/vendor/github.com/spf13/cobra/command.go:968
github.com/vanilla-os/orchid/cmdr.(*App).Run(0xc000004300?)
	/__w/Ikaros/Ikaros/vendor/github.com/vanilla-os/orchid/cmdr/app.go:97 +0x6d
main.main()
	/__w/Ikaros/Ikaros/main.go:35 +0x405
```

**Comment by mirkobrombin** [comment]
ikaros is no more planned for Orchid, so we can postpone this for the moment
